Table marca {
	id_marca integer [ pk, increment, not null, unique ]
	nombra varchar
	descripcion varchar
}

Table empleada {
	id_empleada integer [ pk, increment, not null, unique ]
	nombre varchar
	apellido varchar
	telefono varchar
	ubicacion text
}

Table cliente {
	id_cliente integer [ pk, increment, not null, unique ]
	nombre varchar
	apellido varchar
	telefono varchar
	id_empleada integer [ not null ]
	id_articulos integer [ not null ]
	id_enseñanza  integer [ not null ]
}

Table servicio {
	id_servicio integer [ pk, increment, not null, unique ]
	Uñas varchar
	Kappin varchar
	Acrilico varchar
	SofGel varchar
	Planchita varchar
	Ondas varchar
	id_cliente integer [ not null ]
}

Table fecha {
	id_horario integer [ pk, increment, not null, unique ]
	hora varchar
	dia varchar
	id_servicio integer [ not null ]
}

Table articulos {
	id_articulos integer [ pk, increment, not null, unique ]
	stock integer [ not null ]
	nombre varchar
	vencimiento varchar
	precio_compa varchar
	id_marca integer [ not null ]
}

Table clases {
	id_enseñanza integer [ pk, increment, not null, unique ]
	id_herremientas integer [ not null ]
	materiale_consumo decimal
	agenda varchar
	alumnos varchar
	id_tipo integer [ not null ]
}

Table herramientas {
	id_herramienta integer [ pk, increment, not null, unique ]
	tipo varchar
	id_marca integer [ not null ]
	cantidad varchar
	precio decimal
}

Table stock {
	id_stock integer [ pk, increment, not null, unique ]
	catidad decimal
	lugar varchar
}

Table tipo_clase {
	id_tipo integer [ pk, increment, not null, unique ]
	peinados varchar
	maquillaje varchar
	maquillaje_artistico varchar
}

Ref fk_empleada_id_empleada_cliente {
	empleada.id_empleada < cliente.id_empleada [ delete: restrict, update: cascade ]
}

Ref fk_cliente_id_empleada_servicio {
	cliente.id_empleada < servicio.id_cliente [ delete: restrict, update: cascade ]
}

Ref fk_servicio_id_servicio_fecha {
	servicio.id_servicio < fecha.id_servicio [ delete: cascade, update: restrict ]
}

Ref fk_cliente_id_articulos_articulos {
	cliente.id_articulos < articulos.id_articulos [ delete: restrict, update: cascade ]
}

Ref fk_enseñanza_id_herremientas_herramientas {
	clases.id_herremientas < herramientas.id_herramienta [ delete: restrict, update: cascade ]
}

Ref fk_cliente_id_enseñanza _enseñanza {
	cliente.id_enseñanza  < clases.id_enseñanza [ delete: restrict, update: cascade ]
}

Ref fk_articulos_stock_stock {
	articulos.stock < stock.id_stock [ delete: restrict, update: cascade ]
}

Ref fk_clases_id_tipo_tipo_clase {
	clases.id_tipo < tipo_clase.id_tipo [ delete: restrict, update: cascade ]
}

Ref fk_herramientas_marca_marca {
	herramientas.id_marca < marca.id_marca [ delete: restrict, update: cascade ]
}

Ref fk_articulos_id_marca_marca {
	articulos.id_marca < marca.id_marca [ delete: restrict, update: cascade ]
}